spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FinalProject
    username: postgres
    password: Na260206
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


secret: iloveyouanditellityoubutyourreacthionnotsocgoo
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#logging:
#  level:
#    org.springframework.web.servlet.mvc.method.annotation: DEBUG
#    org.springframework.web.servlet.handler: DEBUG
